use std::fs::File;
use std::io::{Result, Write};

fn main() {
  build_vector().unwrap();
}

fn build_vector() -> Result<()> {
  let mut f = File::create("src/trap/vector.S")?;
  writeln!(f, "# generated by build.rs - do not edit")?;
  writeln!(f, ".section .text")?;
  for i in 0..256 {
    writeln!(f, "vector{}:", i)?;
    if !(i == 8 || (10..=14).contains(&i) || i == 17) {
      writeln!(f, "\tpush 0")?;
    }
    writeln!(f, "\tpush {}", i)?;
    writeln!(f, "\tjmp __trap_entry")?;
  }
  writeln!(f, "\n.section .rodata")?;
  writeln!(f, ".global __vectors")?;
  writeln!(f, "__vectors:")?;
  for i in 0..256 {
    writeln!(f, "\t.quad vector{}", i)?;
  }
  Ok(())
}
